### ISSUE TITLE
 card operation

### ISSUE THREAD

**Issue by thetux07** [custom-cards/group-element#2]
hello,
i'm sorry but i don't understend where put the entities ?!
for exemple, for the cover in your demo picture, where you inquiere it ?
thank you
best regards

**Comment by vakilando** [comment]
look at my configuration in [issue 3](https://github.com/custom-cards/group-element/issues/3).
and tell me if it works or if you have the thame issue as I have.

**Comment by yosilevy** [comment]
Didn't see this issue sorry. As I responded on HASS user groups - you must ONLY use the elements used within picture-elements.
