### ISSUE TITLE
d.setConfig is not a function

### ISSUE THREAD

**Issue by vakilando** [custom-cards/group-element#3]
I get the error: **_d.setConfig is not a function_**

HA version 0.110.4 running with docker
configuration.yaml: 
`    - url: /local/group-element-bundle.js?v=0.5.0
      type: module`

frontend.yaml:
`  javascript_version: latest`

ui-lovelace.yaml:
`          #       icon: mdi:disc

          - type: picture-elements
            image: /local/bilder/wohnzimmer-BS3.jpg
            elements:
              # first group - with grouping_code of 1
              - type: 'custom:group-element'
                visible: false
                toggle_tap: true
                grouping_code: 1
                style:
                  # the group style determines the hotspot
                  height: 40%
                  left: 41%
                  top: 30%
                  width: 25%
                elements:
                  # your elements go here - their size/position is relative to the group
                  - type: entities
                    style:
                      #height: 40%
                      left: 50%
                      top: 50%
                      #width: 25%
                    # title: Aufwachlicht Schlafzimmer
                    # show_header_toggle: false
                    entities:
                      - light.feba
                      #- light.wohnzimmerdecke
                      #- light.ecklicht
                elements_pos:
                  # the elements_pos style determine the location of the elements
                  left: 10%
                  top: 65%
                  width: 80%
                  height: 30%
                  transform: none
                  background-color: 'rgba(255, 255, 255, 0.6)'
                  border-radius: 10px
                close_button:
                  # the close button determines the location of the close button
                  show: true
                  style:
                    background-color: 'rgba(255, 255, 255, 0.6)'
                    border-color: grey
                    border-radius: 0px
                    border: 0.5px solid red
                    left: 2%
                    top: 62%
                    transform: none

              # second group - also with grouping_code of 1
              # second group's element_pos & close_button is identical to group 1 and they share the 
              # same real-estate so they need to not be shown together
              - type: 'custom:group-element'
                visible: false
                toggle_tap: true
                grouping_code: 1
                style:
                  # the group style determines the hotspot
                  height: 40%
                  left: 68%
                  top: 30%
                  width: 25%
                elements:
                  # your elements go here - their size/position is relative to the group
                  - type: entities
                    style:
                      #height: 40%
                      left: 80%
                      top: 80%
                      #width: 25%
                    # title: Aufwachlicht Schlafzimmer
                    # show_header_toggle: false
                    entities:
                      #- light.arbeitszimmerdecke
                      - light.hue_lightstrip_plus_1
                      #- light.wohnflur
                elements_pos:
                  # the elements_pos style determine the location of the elements
                  left: 10%
                  top: 65%
                  width: 80%
                  height: 30%
                  transform: none
                  background-color: 'rgba(255, 255, 255, 0.6)'
                  border-radius: 10px
                close_button:
                  # the close button determines the location of the close button
                  show: true
                  style:
                    background-color: 'rgba(255, 255, 255, 0.6)'
                    border-color: black
                    border-radius: 10px
                    border-style: solid
                    left: 1%
                    top: 69%
                    transform: none`

**Comment by yosilevy** [comment]
Didn't see this issue sorry. As I responded on HASS user groups - you must ONLY use the elements used within picture-elements.
