### ISSUE TITLE
the group is not showing on mobile

### ISSUE THREAD

**Issue by bobzer** [custom-cards/group-element#4]
Hi, 

I love your great work, it works great on my desktop but not on my mobile. 
the group element don't become visible 
here is the config i'm using : 
`
  - close_button:
      show: true
      style:
        background-color: 'rgba(255, 255, 255, 0.6)'
        border-color: black
        border-radius: 10px
        border-style: solid
        left: 88%
        top: 2%
        transform: scale(0.7)
    elements:
      - style:
          left: 17%
          top: 5%
          transform: scale(1.5)
        text: Prise de la bibliothèque
        type: 'custom:text-element'
      - entity: switch.swidget_plug_library
        hold_action:
          action: more-info
        style:
          left: 89%
          top: 80%
        tap_action:
          action: toggle
        type: state-icon
      - entity: switch.library_automation
        style:
          left: 90%
          top: 50%
        type: state-icon
      - conditions:
          - entity: switch.library_automation
            state: 'on'
        elements:
          - entity: input_datetime.library_light_turn_on
            style:
              left: 50%
              top: 48%
            type: state-label
          - style:
              left: 10%
              top: 40%
              transform: scale(1.2)
            text: 'Allumage :'
            type: 'custom:text-element'
          - entity: sensor.library_light_duration_hours
            style:
              left: 50%
              top: 75%
            tap_action: none
            type: state-label
          - entity: input_number.library_light_duration_mins
            style:
              color: transparent
              left: 50%
              top: 75%
            type: state-label
          - style:
              left: 10%
              top: 67%
              transform: scale(1.2)
            text: 'Durée :'
            type: 'custom:text-element'
        type: conditional
    elements_pos:
      background-color: 'rgba(255, 255, 255, 0.85)'
      border-radius: 10px
      height: 70%
      left: 8%
      top: 16%
      transform: none
      width: 60%
    style:
      left: 92%
      top: 83%
    toggle_area_elements:
      - entity: switch.swidget_plug_library
        tap_action: none
        type: state-icon
    toggle_tap: true
    type: 'custom:group-element'
    visible: false`

thank you

**Comment by yosilevy** [comment]
Fixed in 0.6.0. Internal hass change broke it.
