### ISSUE TITLE
style, background-image

### ISSUE THREAD

**Issue by gribouk** [custom-cards/group-element#8]
Hello.

I try to set background-image instead of background-color in the style properties of the elements_pos but with no success. This is how I try to do that:
   
   elements_pos:
      left: 1%
      top: 1%
      width: 100%
      height: 100%
      transform: none     
      background-image: local/rescources/pictures/dan_photo.jpg
      background-color: 'rgba(55, 255, 255, 0.9)'
      border-radius: 50px 

Any suggestions what I do wrong?

**Comment by yosilevy** [comment]
You need url("local/...")
See https://www.w3schools.com/cssref/pr_background-image.php
