### ISSUE TITLE
Uncaught TypeError: c.setConfig is not a function

### ISSUE THREAD

**Issue by starkillerOG** [custom-cards/group-element#9]
@yosilevy since HomeAssistant 2022.09 I am seeing this error in the HomeAssistant log:
```
Logger: frontend.js.latest.202209072
Source: components/system_log/__init__.py:227
http://192.168.1.IP:8123/hacsfiles/group-element/group-element-bundle.js?hacstag=179491130091:1:1383 Uncaught TypeError: c.setConfig is not a function
```

I think this is causing my screen to be white instead of just loading the relevant HomeAssistant page.

Could you maybe have a look?

**Comment by yosilevy** [comment]
Sorry for not seeing this. This just means your configuration is invalid. If you need help post it.
